'use client'

import { useEffect, useState } from 'react'
import { useSession } from 'next-auth/react'
import { resolveApiBaseUrl } from '@/lib/api-base-url'
import { formatNaira } from '@/lib/formatters'

type Forecast = {
  id: string
  periodDays: number
  projectedRevenue: number
  confidenceScore: number
  generatedAt: string
  riskFlag?: string | null
}

function asList<T>(payload: unknown): T[] {
  if (Array.isArray(payload)) {
    return payload as T[]
  }

  if (payload && typeof payload === 'object' && 'data' in payload) {
    const wrapped = (payload as { data?: unknown }).data
    return Array.isArray(wrapped) ? (wrapped as T[]) : []
  }

  return []
}

export default function ForecastsPage() {
  const { data: session } = useSession()
  const apiBase = resolveApiBaseUrl()
  const accessToken = (session?.user as { accessToken?: string } | undefined)?.accessToken

  const [forecasts, setForecasts] = useState<Forecast[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    if (!accessToken) {
      return
    }

    const headers = new Headers()
    headers.set('Authorization', `Bearer ${accessToken}`)
    headers.set('Content-Type', 'application/json')

    async function loadForecasts() {
      setLoading(true)
      setError('')
      try {
        const res = await fetch(
          `${apiBase}/api/v1/forecasts`,
          { headers },
        )

        if (!res.ok) {
          throw new Error('Failed to load forecasts')
        }

        const payload = await res.json()
        const records = asList<Forecast>(payload)

        // Ensure we have 30/60/90 day forecasts
        const sorted = records
          .sort((a, b) => a.periodDays - b.periodDays)
          .slice(0, 3)
        setForecasts(sorted)
      } catch {
        setError('Unable to load forecasts right now.')
      } finally {
        setLoading(false)
      }
    }

    void loadForecasts()
  }, [accessToken, apiBase])

  const riskAlert = forecasts.find((f) => f.riskFlag)?.riskFlag

  return (
    <div className="space-y-6">
      <header className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <h1 className="text-2xl font-bold text-slate-900">Revenue Forecasts</h1>
        <p className="mt-2 text-sm text-slate-600">
          Projected revenue windows generated by the Revenue Forecasting Agent.
        </p>
      </header>

      {error ? (
        <section className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">
          {error}
        </section>
      ) : null}

      {loading ? (
        <section className="rounded-xl border border-slate-200 bg-white p-6 text-center text-sm text-slate-600">
          Loading forecasts...
        </section>
      ) : forecasts.length === 0 ? (
        <section className="rounded-xl border border-slate-200 bg-white p-6 text-center text-sm text-slate-600">
          No forecast data available yet. Run the Revenue Forecasting Agent to generate predictions.
        </section>
      ) : (
        <>
          <section className="grid gap-4 md:grid-cols-3">
            {forecasts.map((item) => (
              <article
                key={item.id}
                className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"
              >
                <p className="text-sm text-slate-500">
                  {item.periodDays}-day window
                </p>
                <p className="mt-2 text-2xl font-bold text-slate-900 font-mono">
                  {formatNaira(item.projectedRevenue)}
                </p>
                <p className="mt-2 text-xs text-slate-600">
                  Confidence: {(item.confidenceScore * 100).toFixed(0)}%
                </p>
              </article>
            ))}
          </section>

          {riskAlert ? (
            <article className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">
              {riskAlert}
            </article>
          ) : null}
        </>
      )}
    </div>
  )
}
