const forecasts = [
  { period: '30 days', projected: 'NGN 22,600,000', confidence: '87%' },
  { period: '60 days', projected: 'NGN 44,800,000', confidence: '81%' },
  { period: '90 days', projected: 'NGN 67,300,000', confidence: '76%' },
]

export default function ForecastsPage() {
  return (
    <div className="space-y-6">
      <header className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <h1 className="text-2xl font-bold text-slate-900">Revenue Forecasts</h1>
        <p className="mt-2 text-sm text-slate-600">Projected revenue windows generated by the Revenue Forecasting Agent.</p>
      </header>

      <section className="grid gap-4 md:grid-cols-3">
        {forecasts.map((item) => (
          <article key={item.period} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
            <p className="text-sm text-slate-500">{item.period}</p>
            <p className="mt-2 text-2xl font-bold text-slate-900 font-mono">{item.projected}</p>
            <p className="mt-1 text-xs text-slate-600">Confidence: {item.confidence}</p>
          </article>
        ))}
      </section>

      <article className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">
        Forecast risk flag: current pace indicates a shortfall of NGN 1.2M vs monthly target.
      </article>
    </div>
  )
}
